version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
    target-branch: "dev"
    cooldown:
      default-days: 7
      semver-major-days: 30
      semver-minor-days: 14
      semver-patch-days: 5
    groups:
      angular:
        patterns:
          - '@angular*'
      blocknote:
        patterns:
          - '@blocknote/*'
      fullcalendar:
        patterns:
          - '@fullcalendar/*'
      html-eslint:
        patterns:
          - '@html-eslint/*'
      ng-select:
        patterns:
          - '@ng-select/*'
      appsignal:
        patterns:
          - '@appsignal/*'
      react:
        patterns:
          - 'react'
          - 'react-dom'
          - '@types/react'
          - '@types/react-dom'
    ignore:
      - dependency-name: "@angular*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@openproject/octicons"
      - dependency-name: "@openproject/primer-view-components"
      - dependency-name: "@primer/primitives"
      - dependency-name: "@primer/css"
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "dev"
    cooldown:
      default-days: 7
      semver-major-days: 30
      semver-minor-days: 14
      semver-patch-days: 5
    groups:
      aws-gems:
        patterns:
          - "aws-*"
    ignore:
      - dependency-name: "openproject-octicons"
      - dependency-name: "openproject-octicons_helper"
      - dependency-name: "openproject-primer_view_components"
  - package-ecosystem: "npm"
    directory: "/extensions/op-blocknote-hocuspocus"
    schedule:
      interval: "weekly"
    target-branch: "dev"
    cooldown:
      default-days: 7
      semver-major-days: 30
      semver-minor-days: 14
      semver-patch-days: 5
    commit-message:
      prefix: "deps(hocuspocus)"
    labels:
      - "dependencies"
    groups:
      npm-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "dev"
    cooldown:
      default-days: 7
